// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// dotenv/config só carrega .env. Next.js também carrega .env.local por cima
// (convenção dele, não do dotenv) — replicamos aqui pra `prisma migrate
// deploy`/`studio` funcionarem com o Postgres local sem passar DATABASE_URL
// na mão. Não afeta a Vercel: lá não existe .env.local, as env vars vêm da
// própria plataforma.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
